### PR TITLE
Slightly Modified High Airflow Case

### PR DESCRIPTION
**Pull request by Judman**
Removed the circular supports the extended all the way to the build plate and left small bumps at the top of the case. Replaced with slightly wider and flatter supports that fit within the case constraints. Also slightly enlarged the PCB groove. I found it way too tight and ended up ripping off a batter holder and pads during removal.

### CODE REVIEW

**Comment by Judman** [comment]
This is my first ever pull request. I hope this is acceptable.

**Comment by rbaron** [comment]
Thanks @Judman -- looks like great improvements. Can I ask you to replace the existing file instead? We have both an stl and 3mf, I'm fine removing both and just creating a new stl. 

Tks!

**Comment by Judman** [comment]
@rbaron I think I made the necessary changes. I generated a .3mf as well, in case that is a preferred format. I do not have any experience with 3mf. If someone wants to validate before merging.

Thanks!

**Comment by rbaron** [comment]
Thanks @Judman, I just opened both files here and they look great. If you have any photos with them I'll invite you to post to our community gallery in #19.

Tks again!

**Pull request merged**
