### PR TITLE
Update Zigbee example to work with SDK 2.2.0

### LINKED ISSUE #94: Zigbee sample fails to build
While trying to build for an nrf 52840-1.2 with nrf connect sdk 2.2.0, I'm getting the following error from CMake:

```
warning: IEEE802154_NRF5_FCS_IN_LENGTH (defined at drivers/ieee802154/Kconfig.nrf5:65) has direct dependencies IEEE802154_NRF5 && IEEE802154 with value n, but is currently being y-selected by the following symbols:
 - NET_L2_ZIGBEE (defined at C:/ncs/v2.2.0/nrf\subsys\zigbee/Kconfig:29), with value y, direct dependencies NETWORKING && ZIGBEE (value: y), and select condition NETWORKING && ZIGBEE (value: y)

error: Aborting due to Kconfig warnings

CMake Error at C:/ncs/v2.2.0/zephyr/cmake/modules/kconfig.cmake:328 (message):
```

Unfortunately, I'm unfamiliar with CMake and Kconfig. Any help would be appreciated.

### PR DESCRIPTION
**Pull request by MJDSys**
The new SDK requires 802.15.4 to be enabled in the board DTS file.

Also disable IPv6 explicitly to avoid compile errors related to its network stack, since it is not used currently.

Closes #94

### CODE REVIEW

**Comment by rbaron** [comment]
Awesome. Thanks for looking into it and sharing the fix. 

Apparently the 2.1 sdk is not happy about it, so we could bump the GitHub actions version to 2.2 too (also the devcontainer.json and wiki docs). I think it should be enough to update the Docker image tag in these 3 places.

**Comment by MJDSys** [comment]
I've updated the PR with the changes, but I don't believe I can modify the wiki myself.

Also I've been playing around with the zigbee software and would like to help improve it.  Would you prefer for me to create an issue to discuss?

And thanks for providing this awesome project!

**Comment by rbaron** [comment]
Perfect, thanks! Please feel totally free to create an issue or PR with your ideas for improvement.

**Comment by MJDSys** [comment]
Hey @rbaron, just wanted to mention I hadn't filed an issue as I was getting my debugger setup to make sure my ideas made sense.  I thought there might have been a power issue but now I'm suspicious about the batteries.  I'm digging some more on my side and I'll create issues/prs as appropriate based on my findings, but I didn't want you to think I forgot.

Thanks again for this project!

**Pull request merged**
