### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by rbaron**
As endearing as it is to get unactionable hate messages, I would rather we focus our efforts on having fun and fostering a small, great, positive, welcoming community, as it's has been so far.

This code of conduct is from https://www.contributor-covenant.org/, based on Mozilla's. I hope we never have to enforce it, and it sucks that we even have to think about these things. But at least this makes it a little more explicit about what's unacceptable behavior.

### CODE REVIEW

**Comment by drspangle** [comment]
This is a good idea. One thing this doesn't include is a requirement to delete hate messages. I'm fine with this how it is but it occurred to me that it could be better to delete that kind of thing in certain cases.

**Comment by foreverimagining** [comment]
It's better to have it and not need it in the future, but there's always at least one person who tries to ruin it for the rest of us.

As for a requirement to delete hate messages, as it is written now, it certainly allows for that to be a response, though doesn't mandate it. I'm not sure it would be a bad idea to try either way, but if it is left out now, it could always be added in later if it begins to seem necessary. Currently, it is fairly broad and allows for conscientious discretion in responsive actions, which I think is a good starting point until you have more examples of what can go wrong.

**Comment by drspangle** [comment]
Ah, that's true, it does mention removal/rejection there. In that case, I think this is really a great thing to have and agree that we already have a situation that warrants enforcement of these standards.

**Comment by rbaron** [comment]
Thanks once again @drspangle and @foreverimagining.

**Comment by foreverimagining** [comment]
Happy to help where I can, and thank you for such a great project.

**Pull request merged**
