### PR TITLE
Add kitspace.yaml

### PR DESCRIPTION
**Pull request by kasbah**
Following on from https://github.com/rbaron/w-parasite/pull/3 I've added the manifest here. Kitspace can also parse your LCSC BOM (though note that it will infer quantities from references, since there is no quantity column). If you want to work on the BOM using the [bom-builder](https://github.com/kitspace/bom-builder)  ([more info](https://kitspace.org/bom-builder)) let me know and I'll give you access.

### CODE REVIEW

**Comment by kasbah** [comment]
Oh, almost forgot. Here is a preview: http://try-b-parasite.preview.kitspace.org/boards/github.com/kitspace-forks/b-parasite/ Let me know if you see any issues with it.

**Comment by erazor666** [comment]
A kitspace integration of this project would be really great, so why no reaction to this PR?

**Comment by rbaron** [comment]
Thanks @kasbah. I'm sorry this slipped through. 

I am not super familiar with kitspace, but it seems interesting and I'm happy to merge it. I'm wondering about two things:

- Does it read from the main branch and generate the gerbers and BOM? I was thinking it would be better to have full, consistent releases with properly versioned, known-to-be-good gerbers, schematics, BOM and assembly files, in the off chance that the main branch has some inconsistencies between these files
- Some 0402 components and the sht sensor are pretty tricky to solder by hand, and I think most people (myself included) would want the board assembled by the fab house (and we only have part numbers for JLCPCB for now). So if I understand it correctly, we'd still need extra fabrication files in most cases

What are your thoughts on these?

**Comment by kasbah** [comment]
Hi @rbaron and thanks @erazor666,

- It does read from the main branch but you can make it read the Gerbers you have plotted, ones that are in the repo, rather than generating them my adding `gerbers: kicad/gerbers`. I'll update the kitspace.yaml on this PR. You can do something similar for the BOM (it's currently looking at `kicad/parasite.csv`). 
- Nothing has been implemented yet, but in the future it would be nice to import directly to JLC Assembly via a link (other assembly services as well).

**Comment by rbaron** [comment]
Awesome. Thanks @kasbah.

**Comment by kasbah** [comment]
It's up! https://kitspace.org/boards/github.com/rbaron/b-parasite/

**Comment by erazor666** [comment]
Wow great, this will help a electronics idiot like myself to get something ordered much simpler. From what little I know about kitspace it looks awesome. 10/10

**Pull request merged**
