### PR TITLE
Added gas exchange holes, cutout for photosensor, pry slots

### PR DESCRIPTION
**Pull request by drspangle**
Updated the STL file and generated a new STEP file.

### CODE REVIEW

**Comment by rbaron** [comment]
Tks @drspangle. I would suggest creating a new STL for this file, since it will not work outdoors. Consider `Top-with-holes.stl` or something like that. Also please make sure the STEP file contains both versions.

**Comment by drspangle** [comment]
>  since it will not work outdoors

@rbaron Clarifying question, does the current case design fit tightly enough that it can work outdoors? If so, I will probably need to iterate further on this design. I assumed it was not liquid-tight currently, since the humidity sensor probably won't work correctly if it is.

**Comment by drspangle** [comment]
I also don't want to cause versioning problems, but it seems to me that having separate folders within the `/case` directory would make sense for the different variations on the case design (with holes, versus without).

**Comment by rbaron** [comment]
I've had one of these cases on my balcony and it holds up okay.

I'm happy to keep it simple if you agree. We can just have two different tops, one with and one without the holes. I'd just like to have both on the step file so people can modify them

**Comment by drspangle** [comment]
Great. Would you be okay with two different STEP files or do you really want both designs embedded in the same file?

**Comment by rbaron** [comment]
Since we already have both the top and bottom on the same step file, it's okay to have the new top there also I think. Tks!

**Comment by drspangle** [comment]
I put both versions into one STEP file, and added the STL file for the modified version separately. This should be good to go.

**Comment by rbaron** [comment]
Thanks @drspangle.

**Pull request merged**
